apiVersion: v1
kind: Pod
metadata:
        name: testcado1
spec:
        containers:
                - name: cadoserver
                  image: jessica948/cadonfs:latest
                  ports:
                          - containerPort: 80
                  command: ['sh', '-c', 'cd /cado-nfs && ./cado-nfs.py 90377629292003121684002147101760858109247336549001090677693 && sleep 30']
        restartPolicy: OnFailure
        imagePullSecrets:
                - name: regcred
