apiVersion: batch/v1
kind: Job
metadata:
    name: polysel
    labels:
        app: server
spec:
    template:
        spec:
            hostname: cadoserver
            containers:
            - name: cadoserver
              image: us-central1-docker.pkg.dev/k8-cado-nfs/cado-nfs-repo/cadonfs:latest
              ports:
                - containerPort: 8012
              command: ['/bin/sh', '-c']
              args: ['cd /cado-nfs && ./cado-nfs.py /etc/config/params tasks.seive.run=false']
              volumeMounts:
                - name: param-volume
                  mountPath: /etc/config
                # - name: server-storage
                #   mountPath: /tmp
            volumes:
                - name: param-volume
                  configMap:
                    name: param-cfg
                # - name: server-storage
                #   persistentVolumeClaim:
                #     claimName: server-storage-claim
            restartPolicy: OnFailure
            imagePullSecrets:
                - name: regcred
    backoffLimit: 2
