apiVersion: batch/v1
kind: Job
metadata:
    name: sieve
spec:
    template:
        metadata:
            labels:
                app: server
        spec:
            containers:
              - name: cadoserver
                image: us-central1-docker.pkg.dev/k8-cado-nfs/cado-nfs-repo/cadonfs:latest
                ports:
                  - containerPort: 8012
                command: ['/bin/sh', '-c']
                args: ['cd /cado-nfs && ./cado-nfs.py tasks.linalg.run=false /etc/config/params; echo "sieving done!"']
                volumeMounts:
                  - name: param-volume
                    mountPath: /etc/config
                  - name: server-storage
                    mountPath: /tmp
            nodeSelector:
                stage: sieve
            volumes:
                - name: param-volume
                  configMap:
                    name: param-cfg
                - name: server-storage
                  persistentVolumeClaim:
                    claimName: server-storage-claim
            restartPolicy: OnFailure
            imagePullSecrets:
                - name: regcred
    backoffLimit: 2
---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: sieveclient
    labels:
        app: client
spec:
    replicas: 4
    selector:
        matchLabels:
            app: client
    template:
        metadata:
            labels:
                app: client
        spec:
            containers:
                - name: cadoclient
                  image: us-central1-docker.pkg.dev/k8-cado-nfs/cado-nfs-repo/cadonfs:latest
                  ports:
                    - containerPort: 80
                  command: ['sh', '-c', 'cd /cado-nfs && ./cado-nfs-client.py --server=http://server-service:8012']
                  resources:
                      requests:
                          cpu: 1.5
            imagePullSecrets:
                - name: regcred
