apiVersion: batch/v1
kind: Job
metadata:
    name: sieve
spec:
    template:
        metadata:
            labels:
                app: server
        spec:
            containers:
              - name: cadoserver
                image: jessica948/cadonfs:latest
                ports:
                  - containerPort: 8012
                command: ['/bin/sh', '-c']
                args: ['cd /cado-nfs && ./cado-nfs.py tasks.linalg.run=false /etc/config/params; echo "sieving done!"']
                volumeMounts:
                  - name: param-volume
                    mountPath: /etc/config
                  - name: server-storage
                    mountPath: /tmp
            nodeSelector:
                type: server
            volumes:
                - name: param-volume
                  configMap:
                    name: param-cfg
                - name: server-storage
                  persistentVolumeClaim:
                    claimName: server-storage-claim
            restartPolicy: OnFailure
            imagePullSecrets:
                - name: regcred
    backoffLimit: 2
