apiVersion: v1
kind: Pod
metadata:
        name: logs
spec:
        containers:
                - name: logs
                  image: ubuntu:latest
                  ports:
                          - containerPort: 80
                  command: ['sh', '-c', 'sleep 3600']
                  volumeMounts:
                          - name: server-storage
                            mountPath: /tmp
        volumes:
            - name: server-storage
              persistentVolumeClaim:
                claimName: server-storage-claim
        restartPolicy: Never
        imagePullSecrets:
                - name: regcred