apiVersion: v1
kind: PersistentVolume
metadata:
  name: server-storage
spec:
  storageClassName: "server"
  capacity:
    storage: 10
  accessModes:
    - ReadWriteOnce
  claimRef:
    namespace: default
    name: server-storage-claim
  gcePersistentDisk:
    pdName: server-pv
    fsType: ext4
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: server-storage-claim
spec:
  storageClassName: "server"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10