apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: server-storage-class
provisioner: kubernetes.io/gce-pd
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true
reclaimPolicy: Delete
parameters:
  type: pd-standard
  fstype: ext4
  replication-type: none
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: server-storage
spec:
  storageClassName: "server-storage-class"
  capacity:
    storage: 10
  accessModes:
    - ReadWriteOnce
  claimRef:
    namespace: default
    name: server-storage-claim
  gcePersistentDisk:
    pdName: server-pv
    fsType: ext4
  persistentVolumeReclaimPolicy: Delete
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: server-storage-claim
spec:
  storageClassName: "server-storage-class"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10