apiVersion: v1
kind: Pod
metadata:
        name: testcado3c
spec:
        containers:
                - name: cadoclient
                  image: jessica948/cadonfs:latest
                  ports:
                          - containerPort: 80
                  command: ['sh', '-c', 'cd /cado-nfs && ./cado-nfs-client.py --server=http://server-service:8012']
        restartPolicy: OnFailure
        imagePullSecrets:
                - name: regcred
